#!/bin/bash
# Refresh editorial/calendar-mirror.json from the live Beachhead calendar.
# Run LOCALLY (needs MARKETING_TOKEN from beachhead/.env.marketing) after any
# calendar change, then commit+push the mirror. The cloud drafter reads the
# mirror because its sandbox cannot reach beachhead.swopme.co.
set -euo pipefail
cd "$(dirname "$0")/.."
: "${MARKETING_TOKEN:?set MARKETING_TOKEN (see beachhead/.env.marketing)}"
curl -sf -H "Authorization: Bearer $MARKETING_TOKEN" "https://beachhead.swopme.co/api/calendar" | python3 -c "
import json,sys,datetime
items=json.load(sys.stdin)['items']
today=datetime.date.today().isoformat()
sel=[i for i in items if i.get('ch')=='blog' and i['d']>=today]
out={'generated':today,'note':'Read-only mirror of the Beachhead content calendar (blog channel) for the cloud drafter, which cannot reach beachhead.swopme.co (egress policy). Refreshed by the local marketing session whenever the calendar changes. The live calendar remains the source of truth — do not edit this file by hand.','items':sel}
open('editorial/calendar-mirror.json','w').write(json.dumps(out,indent=1,ensure_ascii=False))
print('mirrored',len(sel),'blog items')"
